package com.wisdom.common.domain;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Tblregionuser generated by hbm2java
 */
@Entity
@Table(name = "tblUser", uniqueConstraints = @UniqueConstraint(columnNames = "aNumber"))
public class User implements java.io.Serializable {

	private Integer userId;
	private String name;
	private String anumber;

	public User() {
	}

	public User(int userId) {
		this.userId = userId;
	}
	public User(String name, String anumber) {
		this.name = name;
		this.anumber = anumber;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "userId", unique = true, nullable = false)
	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	@Column(name = "name", length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "aNumber", unique = true, length = 20)
	public String getAnumber() {
		return this.anumber;
	}

	public void setAnumber(String anumber) {
		this.anumber = anumber;
	}

}
