package com.wisdom.region.rest.domain;
// Generated Mar 3, 2017 1:40:47 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TblconsistentregionusebranchId generated by hbm2java
 */
@Embeddable
public class ConsistentRegionUseBranchId implements java.io.Serializable {

	private int fkSpecificRegionUseId;
	private int fkGeneralRegionUseId;

	public ConsistentRegionUseBranchId() {
	}

	public ConsistentRegionUseBranchId(int fkSpecificRegionUseId, int fkGeneralRegionUseId) {
		this.fkSpecificRegionUseId = fkSpecificRegionUseId;
		this.fkGeneralRegionUseId = fkGeneralRegionUseId;
	}

	@Column(name = "fkSpecificRegionUseId", nullable = false)
	public int getFkSpecificRegionUseId() {
		return this.fkSpecificRegionUseId;
	}

	public void setFkSpecificRegionUseId(int fkSpecificRegionUseId) {
		this.fkSpecificRegionUseId = fkSpecificRegionUseId;
	}

	@Column(name = "fkGeneralRegionUseId", nullable = false)
	public int getFkGeneralRegionUseId() {
		return this.fkGeneralRegionUseId;
	}

	public void setFkGeneralRegionUseId(int fkGeneralRegionUseId) {
		this.fkGeneralRegionUseId = fkGeneralRegionUseId;
	}

	public boolean equals(Object other) {
		if ((this == other)) {
			return true;
		}
		if ((other == null)) {
			return false;
		}
		if (!(other instanceof ConsistentRegionUseBranchId)) {
			return false;
		}
		ConsistentRegionUseBranchId castOther = (ConsistentRegionUseBranchId) other;

		return (this.getFkSpecificRegionUseId() == castOther.getFkSpecificRegionUseId())
				&& (this.getFkGeneralRegionUseId() == castOther.getFkGeneralRegionUseId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getFkSpecificRegionUseId();
		result = 37 * result + this.getFkGeneralRegionUseId();
		return result;
	}

}
