package com.wisdom.region.rest.domain;
// Generated Mar 3, 2017 1:40:47 AM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Tblconsistentregionuse generated by hbm2java
 */
@Entity
@Table(name = "tblConsistentRegionUse")
public class ConsistentRegionUse implements java.io.Serializable {

	
	private Integer specificRegionUseId;
	private Integer generalRegionUseId;
	
	public ConsistentRegionUse() {
	}
	public ConsistentRegionUse(Integer specificRegionUseId, Integer generalRegionUseId){
		this.specificRegionUseId = specificRegionUseId;
		this.generalRegionUseId = generalRegionUseId;
	}
	
	private Integer id;
	

	public void setSpecificRegionUseId(Integer specificRegionUseId) {
		this.specificRegionUseId = specificRegionUseId;
	}
	public void setGeneralRegionUseId(Integer generalRegionUseId) {
		this.generalRegionUseId = generalRegionUseId;
	}
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	
	@Column(name = "fkSpecificRegionUseId", nullable = false)
	public Integer getSpecificRegionUseId() {
		return this.specificRegionUseId;
	}

	@Column(name = "fkGeneralRegionUseId", nullable = false)
	public Integer getGeneralRegionUseId() {
		return this.generalRegionUseId;
	}
	

	
}
