package com.wisdom.region.rest.domain;
// Generated Mar 3, 2017 1:40:47 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Tblnormalizedregiontitle generated by hbm2java
 */
@Entity
@Table(name = "tblNormalizedRegionTitle")
public class NormalizedRegionTitle implements java.io.Serializable {

	private Integer normalizedRegionTitleId;
	private String title;

	public NormalizedRegionTitle() {
	}

	public NormalizedRegionTitle(String title) {
		this.title = title;
	}


	private Integer id;
	

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "normalizedRegionTitleId", unique = true, nullable = false)
	public Integer getNormalizedRegionTitleId() {
		return this.normalizedRegionTitleId;
	}

	public void setNormalizedRegionTitleId(Integer normalizedRegionTitleId) {
		this.normalizedRegionTitleId = normalizedRegionTitleId;
	}

	@Column(name = "title", length = 500)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

}
