package com.wisdom.region.rest.domain;
// Generated Mar 3, 2017 1:40:47 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Tblnormalizedregiontitleusebranch generated by hbm2java
 */
@Entity
@Table(name = "tblNormalizedRegionTitleUseBranch")
public class NormalizedRegionTitleUseBranch implements java.io.Serializable {

	private NormalizedRegionTitleUseBranchId id;

	public NormalizedRegionTitleUseBranch() {
	}

	public NormalizedRegionTitleUseBranch(NormalizedRegionTitleUseBranchId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "fkNormalizedRegionTitleId", column = @Column(name = "fkNormalizedRegionTitleId")),
			@AttributeOverride(name = "fkRegionUseId", column = @Column(name = "fkRegionUseId")) })
	public NormalizedRegionTitleUseBranchId getId() {
		return this.id;
	}

	public void setId(NormalizedRegionTitleUseBranchId id) {
		this.id = id;
	}

}
