package com.wisdom.region.rest.domain;
// Generated Mar 3, 2017 1:40:47 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Tblregionuser generated by hbm2java
 */
@Entity
@Table(name = "tblRegionUser", uniqueConstraints = @UniqueConstraint(columnNames = "aNumber"))
public class RegionUser implements java.io.Serializable {

	private Integer userId;
	private String name;
	private String anumber;

	public RegionUser() {
	}

	public RegionUser(String name, String anumber) {
		this.name = name;
		this.anumber = anumber;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "userId", unique = true, nullable = false)
	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	@Column(name = "name", length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "aNumber", unique = true, length = 20)
	public String getAnumber() {
		return this.anumber;
	}

	public void setAnumber(String anumber) {
		this.anumber = anumber;
	}

}
