package com.wisdom.region.rest.domain;
// Generated Mar 3, 2017 1:40:47 AM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Tblregiontitlebranch generated by hbm2java
 */
@Entity
@Table(name = "tblRegionTitleBranch")
public class RegionTitleBranch implements java.io.Serializable {

	private Integer regionTitleId;
	private Integer mainRegionTitleId;
	private String title;
	private int fkNormalizedRegionTitleId;

	public RegionTitleBranch() {
	}

	public RegionTitleBranch(int fkNormalizedRegionTitleId) {
		this.fkNormalizedRegionTitleId = fkNormalizedRegionTitleId;
	}

	public RegionTitleBranch(String title, int mainRegionTitleId) {
		this.title = title;
		this.mainRegionTitleId = mainRegionTitleId;
	}
	
	public RegionTitleBranch(String title, int mainRegionTitleId, int fkNormalizedRegionTitleId) {
		this.title = title;
		this.mainRegionTitleId = mainRegionTitleId;
		this.fkNormalizedRegionTitleId = fkNormalizedRegionTitleId;
	}

	
	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "regionTitleId", unique = true, nullable = false)
	public Integer getRegionTitleId() {
		return this.regionTitleId;
	}

	
	@Column(name = "mainRegionTitleId", nullable = true)
	public Integer getMainRegionTitleId() {
		return mainRegionTitleId;
	}

	public void setMainRegionTitleId(Integer mainRegionTitleId) {
		this.mainRegionTitleId = mainRegionTitleId;
	}

	public void setRegionTitleId(Integer regionTitleId) {
		this.regionTitleId = regionTitleId;
	}

	@Column(name = "title", length = 500)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "fkNormalizedRegionTitleId", nullable = true)
	public int getFkNormalizedRegionTitleId() {
		return this.fkNormalizedRegionTitleId;
	}

	public void setFkNormalizedRegionTitleId(int fkNormalizedRegionTitleId) {
		this.fkNormalizedRegionTitleId = fkNormalizedRegionTitleId;
	}

}
