package com.wisdom.region.rest.domain;
// Generated Mar 3, 2017 1:40:47 AM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Tblregionusebranch generated by hbm2java
 */
@Entity
@Table(name = "tblRegionUseBranch")
public class RegionUseBranch implements java.io.Serializable {

	private Integer regionUseId;
	private String ncid;
	private String description;

	public RegionUseBranch() {
	}

	public RegionUseBranch(String ncid, String description) {
		this.ncid = ncid;
		this.description = description;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "regionUseId", unique = true, nullable = false)
	public Integer getRegionUseId() {
		return this.regionUseId;
	}

	public void setRegionUseId(Integer regionUseId) {
		this.regionUseId = regionUseId;
	}

	@Column(name = "ncid", length = 50)
	public String getNcid() {
		return this.ncid;
	}

	public void setNcid(String ncid) {
		this.ncid = ncid;
	}

	@Column(name = "description", length = 500)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
