package com.wisdom.region.rest.domain;
// Generated Mar 3, 2017 1:40:47 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TblregioneditmappingId generated by hbm2java
 */
@Embeddable
public class RegionEditMappingId implements java.io.Serializable {

	private Integer fkEditId;
	private Integer fkRegionTitleId;
	
	public RegionEditMappingId() {
	}

	public RegionEditMappingId(Integer fkEditId, Integer fkRegionTitleId) {
		this.fkEditId = fkEditId;
		this.fkRegionTitleId = fkRegionTitleId;
	}

	@Column(name = "fkEditId")
	public Integer getFkEditId() {
		return this.fkEditId;
	}

	public void setFkEditId(Integer fkEditId) {
		this.fkEditId = fkEditId;
	}

	@Column(name = "fkRegionTitleId")
	public Integer getFkRegionTitleId() {
		return this.fkRegionTitleId;
	}

	public void setFkRegionTitleId(Integer fkRegionTitleId) {
		this.fkRegionTitleId = fkRegionTitleId;
	}

	public boolean equals(Object other) {
		if ((this == other)) {
			return true;
		}
		if ((other == null)) {
			return false;
		}
		if (!(other instanceof RegionEditMappingId)) {
			return false;
		}
		RegionEditMappingId castOther = (RegionEditMappingId) other;

		return ((this.getFkEditId() == castOther.getFkEditId()) || (this.getFkEditId() != null
				&& castOther.getFkEditId() != null && this.getFkEditId().equals(castOther.getFkEditId())))
				&& ((this.getFkRegionTitleId() == castOther.getFkRegionTitleId())
						|| (this.getFkRegionTitleId() != null
								&& castOther.getFkRegionTitleId() != null
								&& this.getFkRegionTitleId()
										.equals(castOther.getFkRegionTitleId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result;
		if(getFkEditId() == null) {
			result += 0;
		} else {
			result += this.getFkEditId().hashCode();
		}
		
		result = 37 * result;
				
		if(getFkRegionTitleId() == null) {
			result += 0;
		} else {
			result += this.getFkRegionTitleId().hashCode();
		}
		result = 37 * result;
		
		return result;
	}

}
