package com.wisdom.region.rest.domain;
// Generated Mar 3, 2017 1:40:47 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Tblregionedit generated by hbm2java
 */
@Entity
@Table(name = "tblRegionEdit")
public class RegionEdit implements java.io.Serializable {

	private Integer editId;
	private byte action;
	private byte status;
	private Date createdOn;
	private Date lastUpdatedOn;
	private int fkBranchId;
	private Integer fkTestId;

	public RegionEdit() {
	}

	public RegionEdit(byte action, byte status, Date createdOn, int fkBranchId) {
		this.action = action;
		this.status = status;
		this.createdOn = createdOn;
		this.fkBranchId = fkBranchId;
	}

	public RegionEdit(byte action, byte status, Date createdOn, Date lastUpdatedOn, int fkBranchId,
			Integer fkTestId) {
		this.action = action;
		this.status = status;
		this.createdOn = createdOn;
		this.lastUpdatedOn = lastUpdatedOn;
		this.fkBranchId = fkBranchId;
		this.fkTestId = fkTestId;
	}

	public RegionEdit(int id) {
		this.editId = editId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "editId", unique = true, nullable = false)
	public Integer getEditId() {
		return this.editId;
	}

	public void setEditId(Integer editId) {
		this.editId = editId;
	}

	@Column(name = "action", nullable = false)
	public byte getAction() {
		return this.action;
	}

	public void setAction(byte action) {
		this.action = action;
	}

	@Column(name = "status", nullable = false)
	public byte getStatus() {
		return this.status;
	}

	public void setStatus(byte status) {
		this.status = status;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createdOn", nullable = false, length = 19)
	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "lastUpdatedOn", length = 19)
	public Date getLastUpdatedOn() {
		return this.lastUpdatedOn;
	}

	public void setLastUpdatedOn(Date lastUpdatedOn) {
		this.lastUpdatedOn = lastUpdatedOn;
	}

	@Column(name = "fkBranchId", nullable = true)
	public int getFkBranchId() {
		return this.fkBranchId;
	}

	public void setFkBranchId(int fkBranchId) {
		this.fkBranchId = fkBranchId;
	}

	@Column(name = "fkTestId", nullable = true)
	public Integer getFkTestId() {
		return this.fkTestId;
	}

	public void setFkTestId(Integer fkTestId) {
		this.fkTestId = fkTestId;
	}

}
