package com.wisdom.region.rest.domain;
// Generated Mar 3, 2017 1:40:47 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Tblregiontitle generated by hbm2java
 */
@Entity
@Table(name = "tblRegionTitle")
public class RegionTitle implements java.io.Serializable {

	private Integer regionTitleId;
	private String title;
	private int fkNormalizedRegionTitleId;
	private byte status;


	public RegionTitle() {
	}

	public RegionTitle(int fkNormalizedRegionTitleId) {
		this.fkNormalizedRegionTitleId = fkNormalizedRegionTitleId;
	}

	public RegionTitle(String title, int fkNormalizedRegionTitleId) {
		this.title = title;
		this.fkNormalizedRegionTitleId = fkNormalizedRegionTitleId;
	}

	private Integer id;

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}
	
	@Column(name = "status", nullable = false)
	public byte getStatus() {
		return this.status;
	}

	public void setStatus(byte status) {
		this.status = status;
	}


	@Column(name = "regionTitleId", unique = true, nullable = false)
	public Integer getRegionTitleId() {
		return this.regionTitleId;
	}

	public void setRegionTitleId(Integer regionTitleId) {
		this.regionTitleId = regionTitleId;
	}

	@Column(name = "title", length = 500)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "fkNormalizedRegionTitleId", nullable = false)
	public int getFkNormalizedRegionTitleId() {
		return this.fkNormalizedRegionTitleId;
	}

	public void setFkNormalizedRegionTitleId(int fkNormalizedRegionTitleId) {
		this.fkNormalizedRegionTitleId = fkNormalizedRegionTitleId;
	}

}
