package com.wisdom.rules.entities;

import java.io.Serializable;
import java.util.Collections;
import java.util.Date;
import java.util.Map;
import java.util.WeakHashMap;

import javax.persistence.Basic;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.hibernate.proxy.HibernateProxy;


/** 
 * Object mapping for hibernate-handled table: tbldatetags.
 * @author autogenerated
 */

@Entity
@Table(name = "tblDateTags")
public class TblDateTags implements Cloneable, Serializable {

	/** Serial Version UID. */
	private static final long serialVersionUID = -558917085L;

	/** Use a WeakHashMap so entries will be garbage collected once all entities 
		referring to a saved hash are garbage collected themselves. */
	private static final Map<Serializable, Integer> SAVED_HASHES =
		Collections.synchronizedMap(new WeakHashMap<Serializable, Integer>());
	
	/** hashCode temporary storage. */
	private volatile Integer hashCode;
	

	/** Field mapping. */
	private Date endDate;
	/** Field mapping. */
	private TblCodeFamily fkCodeFamilyId;
	/** Field mapping. */
	private Integer id = 0; // init for hibernate bug workaround
	/** Field mapping. */
	private Date startDate;
	/** Field mapping. */
	private String test;
	/**
	 * Default constructor, mainly for hibernate use.
	 */
	public TblDateTags() {
		// Default constructor
	} 

	/** Constructor taking a given ID.
	 * @param id to set
	 */
	public TblDateTags(Integer id) {
		this.id = id;
	}
	
	/** Constructor taking a given ID.
	 * @param fkCodeFamilyId Tblcodefamily object;
	 * @param id Integer object;
	 */
	public TblDateTags(TblCodeFamily fkCodeFamilyId, Integer id) {

		this.fkCodeFamilyId = fkCodeFamilyId;
		this.id = id;
	}
	
 


 
	/** Return the type of this class. Useful for when dealing with proxies.
	* @return Defining class.
	*/
	@Transient
	public Class<?> getClassType() {
		return TblDateTags.class;
	}
 

    /**
     * Return the value associated with the column: enddate.
	 * @return A Date object (this.enddate)
	 */
	public Date getEndDate() {
		return this.endDate;
		
	}
	

  
    /**  
     * Set the value related to the column: enddate.
	 * @param endDate the enddate value you wish to set
	 */
	public void setEndDate(final Date endDate) {
		this.endDate = endDate;
	}

    /**
     * Return the value associated with the column: fkcodefamilyid.
	 * @return A Tblcodefamily object (this.fkcodefamilyid)
	 */
	@ManyToOne( cascade = { CascadeType.PERSIST, CascadeType.MERGE }, fetch = FetchType.LAZY )
	@org.hibernate.annotations.Cascade({org.hibernate.annotations.CascadeType.SAVE_UPDATE})
	@Basic( optional = false )
	@JoinColumn(name = "fkCodeFamilyId", nullable = false )
	public TblCodeFamily getFkCodeFamilyId() {
		return this.fkCodeFamilyId;
		
	}
	

  
    /**  
     * Set the value related to the column: fkcodefamilyid.
	 * @param fkCodeFamilyId the fkcodefamilyid value you wish to set
	 */
	public void setFkCodeFamilyId(final TblCodeFamily fkCodeFamilyId) {
		this.fkCodeFamilyId = fkCodeFamilyId;
	}

    /**
     * Return the value associated with the column: id.
	 * @return A Integer object (this.id)
	 */
    @Id 
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Basic( optional = false )
	@Column( name = "id", nullable = false  )
	public Integer getId() {
		return this.id;
		
	}
	

  
    /**  
     * Set the value related to the column: id.
	 * @param id the id value you wish to set
	 */
	public void setId(final Integer id) {
		// If we've just been persisted and hashCode has been
		// returned then make sure other entities with this
		// ID return the already returned hash code
		if ( (this.id == null || this.id == 0) &&
				(id != null) &&
				(this.hashCode != null) ) {
		SAVED_HASHES.put( id, this.hashCode );
		}
		this.id = id;
	}

    /**
     * Return the value associated with the column: startdate.
	 * @return A Date object (this.startdate)
	 */
	public Date getStartDate() {
		return this.startDate;
		
	}
	

  
    /**  
     * Set the value related to the column: startdate.
	 * @param startDate the startdate value you wish to set
	 */
	public void setStartDate(final Date startDate) {
		this.startDate = startDate;
	}

    /**
     * Return the value associated with the column: test.
	 * @return A String object (this.test)
	 */
	@Basic( optional = true )
	@Column( length = 45  )
	public String getTest() {
		return this.test;
		
	}
	

  
    /**  
     * Set the value related to the column: test.
	 * @param test the test value you wish to set
	 */
	public void setTest(final String test) {
		this.test = test;
	}


   /**
    * Deep copy.
	* @return cloned object
	* @throws CloneNotSupportedException on error
    */
    @Override
    public TblDateTags clone() throws CloneNotSupportedException {
		
        final TblDateTags copy = (TblDateTags)super.clone();

		copy.setEndDate(this.getEndDate());
		copy.setFkCodeFamilyId(this.getFkCodeFamilyId());
		copy.setId(this.getId());
		copy.setStartDate(this.getStartDate());
		copy.setTest(this.getTest());
		return copy;
	}
	


	/** Provides toString implementation.
	 * @see java.lang.Object#toString()
	 * @return String representation of this class.
	 */
	@Override
	public String toString() {
		StringBuffer sb = new StringBuffer();
		
		sb.append("enddate: " + this.getEndDate() + ", ");
		sb.append("id: " + this.getId() + ", ");
		sb.append("startdate: " + this.getStartDate() + ", ");
		sb.append("test: " + this.getTest());
		return sb.toString();		
	}


	/** Equals implementation. 
	 * @see java.lang.Object#equals(java.lang.Object)
	 * @param aThat Object to compare with
	 * @return true/false
	 */
	@Override
	public boolean equals(final Object aThat) {
		Object proxyThat = aThat;
		
		if ( this == aThat ) {
			 return true;
		}

		
		if (aThat instanceof HibernateProxy) {
 			// narrow down the proxy to the class we are dealing with.
 			try {
				proxyThat = ((HibernateProxy) aThat).getHibernateLazyInitializer().getImplementation(); 
			} catch (org.hibernate.ObjectNotFoundException e) {
				return false;
		   	}
		}
		if (aThat == null)  {
			 return false;
		}
		
		final TblDateTags that; 
		try {
			that = (TblDateTags) proxyThat;
			if ( !(that.getClassType().equals(this.getClassType()))){
				return false;
			}
		} catch (org.hibernate.ObjectNotFoundException e) {
				return false;
		} catch (ClassCastException e) {
				return false;
		}
		
		
		boolean result = true;
		result = result && (((this.getId() == null) && ( that.getId() == null)) || (this.getId() != null  && this.getId().equals(that.getId())));
		result = result && (((getEndDate() == null) && (that.getEndDate() == null)) || (getEndDate() != null && getEndDate().equals(that.getEndDate())));
		result = result && (((getFkCodeFamilyId() == null) && (that.getFkCodeFamilyId() == null)) || (getFkCodeFamilyId() != null && getFkCodeFamilyId().getId().equals(that.getFkCodeFamilyId().getId())));	
		result = result && (((getStartDate() == null) && (that.getStartDate() == null)) || (getStartDate() != null && getStartDate().equals(that.getStartDate())));
		result = result && (((getTest() == null) && (that.getTest() == null)) || (getTest() != null && getTest().equals(that.getTest())));
		return result;
	}
	
	/** Calculate the hashcode.
	 * @see java.lang.Object#hashCode()
	 * @return a calculated number
	 */
	@Override
	public int hashCode() {
		if ( this.hashCode == null ) {
			synchronized ( this ) {
				if ( this.hashCode == null ) {
					Integer newHashCode = null;

					if ( getId() != null ) {
					newHashCode = SAVED_HASHES.get( getId() );
					}
					
					if ( newHashCode == null ) {
						if ( getId() != null && getId() != 0) {
							newHashCode = getId();
						} else {

						}
					}
					
					this.hashCode = newHashCode;
				}
			}
		}
	return (Integer) this.hashCode;
	}
	

	
}
