package com.wisdom.rules.entities;

import java.io.Serializable;
import java.util.Collections;
import java.util.TreeSet;
import java.util.Map;
import java.util.Set;
import java.util.WeakHashMap;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.OrderBy;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.hibernate.proxy.HibernateProxy;


/** 
 * Object mapping for hibernate-handled table: tblslots.
 * @author autogenerated
 */

@Entity
@Table(name = "tblSlots")
public class TblSlots implements Cloneable, Serializable{

	/** Serial Version UID. */
	private static final long serialVersionUID = -558917070L;

	/** Use a WeakHashMap so entries will be garbage collected once all entities 
		referring to a saved hash are garbage collected themselves. */
	private static final Map<Serializable, Integer> SAVED_HASHES =
		Collections.synchronizedMap(new WeakHashMap<Serializable, Integer>());
	
	/** hashCode temporary storage. */
	private volatile Integer hashCode;
	

	/** Field mapping. */
	private Integer id;
	/** Field mapping. */
	private Set<TblCodeDefinitions> tblCodeDefinitions = new TreeSet<TblCodeDefinitions>();
	
	/** Field mapping. */
	private Set<TblMappingRules> tblMappingRules = new TreeSet<TblMappingRules>();
	
	/** Field mapping. */
	private Set<TblVerbFrameRules> tblVerbFrameRules = new TreeSet<TblVerbFrameRules>();
	

	/** Field mapping. */
	private String value;
	/**
	 * Default constructor, mainly for hibernate use.
	 */
	public TblSlots() {
		// Default constructor
	} 

	/** Constructor taking a given ID.
	 * @param id to set
	 */
	public TblSlots(Integer id) {
		this.id = id;
	}
	
	/** Constructor taking a given ID.
	 * @param id Integer object;
	 * @param value String object;
	 */
	public TblSlots(Integer id, String value) {

		this.id = id;
		this.value = value;
	}
	
 


 
	/** Return the type of this class. Useful for when dealing with proxies.
	* @return Defining class.
	*/
	@Transient
	public Class<?> getClassType() {
		return TblSlots.class;
	}
 

    /**
     * Return the value associated with the column: id.
	 * @return A Integer object (this.id)
	 */
    @Id 
	@Basic( optional = false )
	@Column( name = "id", nullable = false  )
	public Integer getId() {
		return this.id;
		
	}
	

  
    /**  
     * Set the value related to the column: id.
	 * @param id the id value you wish to set
	 */
	public void setId(final Integer id) {
		// If we've just been persisted and hashCode has been
		// returned then make sure other entities with this
		// ID return the already returned hash code
		if ( (this.id == null || this.id == 0) &&
				(id != null) &&
				(this.hashCode != null) ) {
		SAVED_HASHES.put( id, this.hashCode );
		}
		this.id = id;
	}

    /**
     * Return the value associated with the column: tblCodeDefinitions.
	 * @return A Set&lt;TblCodeDefinitions&gt; object (this.tblCodeDefinitions)
	 */
	@ManyToMany(mappedBy = "tblSlots")
	@OrderBy("id ASC")
	public Set<TblCodeDefinitions> getTblCodeDefinitions() {
		return this.tblCodeDefinitions;
		
	}
	
	/**
	 * Adds a bi-directional link of type TblCodeDefinitions to the tblCodeDefinitions set.
	 * @param tblCodeDefinitions item to add
	 */
	public void addTblCodeDefinitions(TblCodeDefinitions tblCodeDefinitions) {
		this.tblCodeDefinitions.add(tblCodeDefinitions);
	}

  
    /**  
     * Set the value related to the column: tblCodeDefinitions.
	 * @param tblCodeDefinitions the tblCodeDefinitions value you wish to set
	 */
	public void setTblCodeDefinitions(final Set<TblCodeDefinitions> tblCodeDefinitions) {
		this.tblCodeDefinitions = tblCodeDefinitions;
	}

    /**
     * Return the value associated with the column: value.
	 * @return A String object (this.value)
	 */
	@Basic( optional = false )
	@Column( nullable = false, length = 45  )
	public String getValue() {
		return this.value;
		
	}
	

  
    /**  
     * Set the value related to the column: value.
	 * @param value the value value you wish to set
	 */
	public void setValue(final String value) {
		this.value = value;
	}


   /**
    * Deep copy.
	* @return cloned object
	* @throws CloneNotSupportedException on error
    */
    @Override
    public TblSlots clone() throws CloneNotSupportedException {
		
        final TblSlots copy = (TblSlots)super.clone();

		copy.setId(this.getId());
		if (this.getTblCodeDefinitions() != null) {
			copy.getTblCodeDefinitions().addAll(this.getTblCodeDefinitions());
		}
		copy.setValue(this.getValue());
		return copy;
	}
	


	/** Provides toString implementation.
	 * @see java.lang.Object#toString()
	 * @return String representation of this class.
	 */
	@Override
	public String toString() {
		StringBuffer sb = new StringBuffer();
		
		sb.append("id: " + this.getId() + ", ");
		sb.append("value: " + this.getValue());
		return sb.toString();		
	}


	/** Equals implementation. 
	 * @see java.lang.Object#equals(java.lang.Object)
	 * @param aThat Object to compare with
	 * @return true/false
	 */
	@Override
	public boolean equals(final Object aThat) {
		Object proxyThat = aThat;
		
		if ( this == aThat ) {
			 return true;
		}

		
		if (aThat instanceof HibernateProxy) {
 			// narrow down the proxy to the class we are dealing with.
 			try {
				proxyThat = ((HibernateProxy) aThat).getHibernateLazyInitializer().getImplementation(); 
			} catch (org.hibernate.ObjectNotFoundException e) {
				return false;
		   	}
		}
		if (aThat == null)  {
			 return false;
		}
		
		final TblSlots that; 
		try {
			that = (TblSlots) proxyThat;
			if ( !(that.getClassType().equals(this.getClassType()))){
				return false;
			}
		} catch (org.hibernate.ObjectNotFoundException e) {
				return false;
		} catch (ClassCastException e) {
				return false;
		}
		
		
		boolean result = true;
		result = result && (((this.getId() == null) && ( that.getId() == null)) || (this.getId() != null  && this.getId().equals(that.getId())));
		result = result && (((getValue() == null) && (that.getValue() == null)) || (getValue() != null && getValue().equals(that.getValue())));
		return result;
	}
	
	/** Calculate the hashcode.
	 * @see java.lang.Object#hashCode()
	 * @return a calculated number
	 */
	@Override
	public int hashCode() {
		if ( this.hashCode == null ) {
			synchronized ( this ) {
				if ( this.hashCode == null ) {
					Integer newHashCode = null;

					if ( getId() != null ) {
					newHashCode = SAVED_HASHES.get( getId() );
					}
					
					if ( newHashCode == null ) {
						if ( getId() != null && getId() != 0) {
							newHashCode = getId();
						} else {

						}
					}
					
					this.hashCode = newHashCode;
				}
			}
		}
	return (Integer) this.hashCode;
	}

	@ManyToMany(mappedBy = "tblSlots")
	@OrderBy("id ASC")
	public Set<TblMappingRules> getTblMappingRules() {
		return tblMappingRules;
	}

	public void setTblMappingRules(Set<TblMappingRules> tblMappingRules) {
		this.tblMappingRules = tblMappingRules;
	}

	public void addTblMappingRules(TblMappingRules tblMappingRules) {
		this.tblMappingRules.add(tblMappingRules);
	}
	
	
	@ManyToMany(mappedBy = "tblSlots")
	@OrderBy("id ASC")
	public Set<TblVerbFrameRules> getTblVerbFrameRules() {
		return tblVerbFrameRules;
	}

	public void setTblVerbFrameRules(Set<TblVerbFrameRules> tblVerbFrameRules) {
		this.tblVerbFrameRules = tblVerbFrameRules;
	}
	
	public void addTblVerbFrameRules(TblVerbFrameRules tblVerbFrameRules) {
		this.tblVerbFrameRules.add(tblVerbFrameRules);
	}
	

	
}
