package com.wisdom.rules.entities;

import java.io.Serializable;
import java.util.Collections;
import java.util.Map;
import java.util.WeakHashMap;

import javax.persistence.Basic;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.hibernate.proxy.HibernateProxy;


/** 
 * Object mapping for hibernate-handled table: tblverbframeactions.
 * @author autogenerated
 */

@Entity
@Table(name = "TblVerbFrameActions")
public class TblVerbFrameActions implements Cloneable, Serializable{

	/** Serial Version UID. */
	private static final long serialVersionUID = -558917069L;

	/** Use a WeakHashMap so entries will be garbage collected once all entities 
		referring to a saved hash are garbage collected themselves. */
	private static final Map<Serializable, Integer> SAVED_HASHES =
		Collections.synchronizedMap(new WeakHashMap<Serializable, Integer>());
	
	/** hashCode temporary storage. */
	private volatile Integer hashCode;
	

	/** Field mapping. */
	private String action;
	/** Field mapping. */
	private TblCodeFamily fkCodeFamilyId;
	/** Field mapping. */
	private TblVerbFrames fkVerbFrameId;
	/** Field mapping. */
	private Integer id;
	/** Field mapping. */
	private Byte late;
	/**
	 * Default constructor, mainly for hibernate use.
	 */
	public TblVerbFrameActions() {
		// Default constructor
	} 

	/** Constructor taking a given ID.
	 * @param id to set
	 */
	public TblVerbFrameActions(Integer id) {
		this.id = id;
	}
	
	/** Constructor taking a given ID.
	 * @param fkCodeFamilyId Tblcodefamily object;
	 * @param id Integer object;
	 */
	public TblVerbFrameActions(TblCodeFamily fkCodeFamilyId, Integer id, TblVerbFrames fkVerbFrameId) {

		this.fkVerbFrameId = fkVerbFrameId;
		this.fkCodeFamilyId = fkCodeFamilyId;
		this.id = id;
	}
	
 


 
	/** Return the type of this class. Useful for when dealing with proxies.
	* @return Defining class.
	*/
	@Transient
	public Class<?> getClassType() {
		return TblVerbFrameActions.class;
	}
 

    /**
     * Return the value associated with the column: action.
	 * @return A String object (this.action)
	 */
	@Basic( optional = true )
	@Column( length = 21845  )
	public String getAction() {
		return this.action;
		
	}
	

  
    /**  
     * Set the value related to the column: action.
	 * @param action the action value you wish to set
	 */
	public void setAction(final String action) {
		this.action = action;
	}

    /**
     * Return the value associated with the column: fkcodefamilyid.
	 * @return A Tblcodefamily object (this.fkcodefamilyid)
	 */
	@ManyToOne( cascade = { CascadeType.PERSIST, CascadeType.MERGE }, fetch = FetchType.LAZY )
	@org.hibernate.annotations.Cascade({org.hibernate.annotations.CascadeType.SAVE_UPDATE})
	@Basic( optional = false )
	@JoinColumn(name = "fkCodeFamilyId", nullable = false )
	public TblCodeFamily getFkCodeFamilyId() {
		return this.fkCodeFamilyId;
		
	}
	
    /**
     * Return the value associated with the column: fkVerbFrameId.
	 * @return A Tblcodefamily object (this.fkVerbFrameId)
	 */
	@ManyToOne( cascade = { CascadeType.PERSIST, CascadeType.MERGE }, fetch = FetchType.LAZY )
	@org.hibernate.annotations.Cascade({org.hibernate.annotations.CascadeType.SAVE_UPDATE})
	@Basic( optional = false )
	@JoinColumn(name = "fkVerbFrameId", nullable = false )
	public TblVerbFrames getFkVerbFrameId() {
		return this.fkVerbFrameId;
		
	}
	
  
    /**  
     * Set the value related to the column: fkcodefamilyid.
	 * @param fkCodeFamilyId the fkcodefamilyid value you wish to set
	 */
	public void setFkCodeFamilyId(final TblCodeFamily fkCodeFamilyId) {
		this.fkCodeFamilyId = fkCodeFamilyId;
	}
	
    /**  
     * Set the value related to the column: fkVerbFrameId.
	 * @param fkVerbFrameId the fkVerbFrameId value you wish to set
	 */
	public void setFkVerbFrameId(final TblVerbFrames fkVerbFrameId) {
		this.fkVerbFrameId = fkVerbFrameId;
	}

    /**
     * Return the value associated with the column: id.
	 * @return A Integer object (this.id)
	 */
    @Id 
	@Basic( optional = false )
	@Column( name = "id", nullable = false  )
	public Integer getId() {
		return this.id;
		
	}
	

  
    /**  
     * Set the value related to the column: id.
	 * @param id the id value you wish to set
	 */
	public void setId(final Integer id) {
		// If we've just been persisted and hashCode has been
		// returned then make sure other entities with this
		// ID return the already returned hash code
		if ( (this.id == null || this.id == 0) &&
				(id != null) &&
				(this.hashCode != null) ) {
		SAVED_HASHES.put( id, this.hashCode );
		}
		this.id = id;
	}

    /**
     * Return the value associated with the column: late.
	 * @return A Byte object (this.late)
	 */
	public Byte getLate() {
		return this.late;
		
	}
	

  
    /**  
     * Set the value related to the column: late.
	 * @param late the late value you wish to set
	 */
	public void setLate(final Byte late) {
		this.late = late;
	}


   /**
    * Deep copy.
	* @return cloned object
	* @throws CloneNotSupportedException on error
    */
    @Override
    public TblVerbFrameActions clone() throws CloneNotSupportedException {
		
        final TblVerbFrameActions copy = (TblVerbFrameActions)super.clone();

		copy.setAction(this.getAction());
		copy.setFkCodeFamilyId(this.getFkCodeFamilyId());
		copy.setFkVerbFrameId(this.getFkVerbFrameId());
		copy.setId(this.getId());
		copy.setLate(this.getLate());
		return copy;
	}
	


	/** Provides toString implementation.
	 * @see java.lang.Object#toString()
	 * @return String representation of this class.
	 */
	@Override
	public String toString() {
		StringBuffer sb = new StringBuffer();
		
		sb.append("action: " + this.getAction() + ", ");
		sb.append("id: " + this.getId() + ", ");
		sb.append("late: " + this.getLate());
		return sb.toString();		
	}


	/** Equals implementation. 
	 * @see java.lang.Object#equals(java.lang.Object)
	 * @param aThat Object to compare with
	 * @return true/false
	 */
	@Override
	public boolean equals(final Object aThat) {
		Object proxyThat = aThat;
		
		if ( this == aThat ) {
			 return true;
		}

		
		if (aThat instanceof HibernateProxy) {
 			// narrow down the proxy to the class we are dealing with.
 			try {
				proxyThat = ((HibernateProxy) aThat).getHibernateLazyInitializer().getImplementation(); 
			} catch (org.hibernate.ObjectNotFoundException e) {
				return false;
		   	}
		}
		if (aThat == null)  {
			 return false;
		}
		
		final TblVerbFrameActions that; 
		try {
			that = (TblVerbFrameActions) proxyThat;
			if ( !(that.getClassType().equals(this.getClassType()))){
				return false;
			}
		} catch (org.hibernate.ObjectNotFoundException e) {
				return false;
		} catch (ClassCastException e) {
				return false;
		}
		
		
		boolean result = true;
		result = result && (((this.getId() == null) && ( that.getId() == null)) || (this.getId() != null  && this.getId().equals(that.getId())));
		result = result && (((getAction() == null) && (that.getAction() == null)) || (getAction() != null && getAction().equals(that.getAction())));
		result = result && (((getFkCodeFamilyId() == null) && (that.getFkCodeFamilyId() == null)) || (getFkCodeFamilyId() != null && getFkCodeFamilyId().getId().equals(that.getFkCodeFamilyId().getId())));
		result = result && (((getFkVerbFrameId() == null) && (that.getFkVerbFrameId() == null)) || (getFkVerbFrameId() != null && getFkVerbFrameId().getId().equals(that.getFkVerbFrameId().getId())));
		result = result && (((getLate() == null) && (that.getLate() == null)) || (getLate() != null && getLate().equals(that.getLate())));
		return result;
	}
	
	/** Calculate the hashcode.
	 * @see java.lang.Object#hashCode()
	 * @return a calculated number
	 */
	@Override
	public int hashCode() {
		if ( this.hashCode == null ) {
			synchronized ( this ) {
				if ( this.hashCode == null ) {
					Integer newHashCode = null;

					if ( getId() != null ) {
					newHashCode = SAVED_HASHES.get( getId() );
					}
					
					if ( newHashCode == null ) {
						if ( getId() != null && getId() != 0) {
							newHashCode = getId();
						} else {

						}
					}
					
					this.hashCode = newHashCode;
				}
			}
		}
	return (Integer) this.hashCode;
	}
	

	
}
